USE [BCAVHW]
GO


IF OBJECT_ID('HOST_REPORT') IS NOT NULL
  DROP TABLE HOST_REPORT
GO

CREATE TABLE HOST_REPORT(
	ID INT IDENTITY(1,1) NOT NULL,
	FILENAME NVARCHAR(255) NULL,
	PERSON_ID NVARCHAR(10) NULL,
	PERSON_NAME NVARCHAR(255) NULL,
	PC_ORDER INT NULL,
	HOSTNAME NVARCHAR(100) NULL,
	IPA_DDRESS NVARCHAR(20) NULL,
	USER_NAME NVARCHAR(100) NULL,
	DESCRIPTION NVARCHAR(100) NULL,
	WINDOWS_PRODUCT_ID NVARCHAR(100) NULL,
	WINDOWS_PRODUCT_KEY NVARCHAR(100) NULL,
	SERVICE_PACK NVARCHAR(100) NULL,
	IE_VERSION NVARCHAR(100) NULL,
	MODEL NVARCHAR(100) NULL,
	SYSTEM_TYPE NVARCHAR(100) NULL,
	SERIALN_UMBER NVARCHAR(100) NULL,
	CHASIS NVARCHAR(100) NULL,
	PHYSICAL_MEMORY NVARCHAR(100) NULL
)
GO

IF OBJECT_ID('OPERATING_SYSTEM') IS NOT NULL
  DROP TABLE OPERATING_SYSTEM
GO

CREATE TABLE OPERATING_SYSTEM(
	HOST_ID INT NOT NULL,
	NAME NVARCHAR(100) NULL,
	VERSION NVARCHAR(100) NULL,
	BUILD NVARCHAR(100) NULL,
	INSTALL_DATE NVARCHAR(100) NULL
)
GO

IF OBJECT_ID('BIOS') IS NOT NULL
  DROP TABLE BIOS
GO

CREATE TABLE BIOS(
	HOST_ID INT NOT NULL,
	MANUFACTURER NVARCHAR(100) NULL,
	VERSION NVARCHAR(100) NULL,
	DATE NVARCHAR(100) NULL
)
GO

IF OBJECT_ID('MOTHERBOARD') IS NOT NULL
  DROP TABLE MOTHERBOARD
GO

CREATE TABLE MOTHERBOARD(
	HOST_ID INT NOT NULL,
	MANUFACTURER NVARCHAR(100) NULL,
	PRODUCT NVARCHAR(100) NULL,
	VERSION NVARCHAR(100) NULL
)
GO

IF OBJECT_ID('MONITOR') IS NOT NULL
  DROP TABLE MONITOR
GO

CREATE TABLE MONITOR(
	HOST_ID INT NOT NULL,
	MANUFACTURER NVARCHAR(100) NULL,
	NAME NVARCHAR(100) NULL,
	DIAGONAL NVARCHAR(100) NULL,
	SERIAL_NUMBER NVARCHAR(100) NULL,
	MAX_RESOLUTION NVARCHAR(100) NULL,
	DISPLAY_SIZE NVARCHAR(100) NULL,
	MANUFACTURE_DATE NVARCHAR(100) NULL
)
GO

IF OBJECT_ID('LOCAL_ACCOUNT') IS NOT NULL
  DROP TABLE LOCAL_ACCOUNT
GO

CREATE TABLE LOCAL_ACCOUNT(
	HOST_ID INT NOT NULL,
	CAPTION NVARCHAR(100) NULL,
	NAME NVARCHAR(100) NULL,
	DOMAIN NVARCHAR(100) NULL,
	DESCRIPTION NVARCHAR(100) NULL,
	SID NVARCHAR(100) NULL,
	DISABLED NVARCHAR(100) NULL
)
GO

IF OBJECT_ID('STARTUP') IS NOT NULL
  DROP TABLE STARTUP
GO

CREATE TABLE STARTUP(
	HOST_ID INT NOT NULL,
	NAME NVARCHAR(100) NULL,
	COMMAND NVARCHAR(255) NULL,
	LOCATION NVARCHAR(255) NULL,
	USERNAME NVARCHAR(100) NULL
)
GO

IF OBJECT_ID('PROCESSOR') IS NOT NULL
  DROP TABLE PROCESSOR
GO

CREATE TABLE PROCESSOR(
	HOST_ID INT NOT NULL,
	NAME NVARCHAR(100) NULL,
	MANUFACTURER NVARCHAR(100) NULL,
	MAXCLOCK_SPEED NVARCHAR(100) NULL,
	ARCHITECTURE NVARCHAR(100) NULL,
	L2_CACHE NVARCHAR(100) NULL,
	SOCKET NVARCHAR(100) NULL
)
GO

IF OBJECT_ID('MEMORY_SLOT') IS NOT NULL
  DROP TABLE MEMORY_SLOT
GO

CREATE TABLE MEMORY_SLOT(
	HOST_ID INT NOT NULL,
	CAPACITY NVARCHAR(100) NULL,
	DEVICE_LOCATOR NVARCHAR(100) NULL,
	BANK_LABEL NVARCHAR(100) NULL,
	FORM_FACTOR NVARCHAR(100) NULL,
	MEMORY_TYPE NVARCHAR(100) NULL,
	MANUFACTURER NVARCHAR(100) NULL,
	SPEED NVARCHAR(100) NULL,
	MAX_CAPACITY NVARCHAR(100) NULL
)
GO

IF OBJECT_ID('DISK') IS NOT NULL
  DROP TABLE DISK
GO

CREATE TABLE DISK(
	HOST_ID INT NOT NULL,
	CAPTION NVARCHAR(100) NULL,
	SIZE NVARCHAR(100) NULL,
	MANUFACTURER NVARCHAR(100) NULL,
	INTERFACE_TYPE NVARCHAR(100) NULL,
	MEDIA_TYPE NVARCHAR(100) NULL,
	BYTES_PER_SECTOR NVARCHAR(100) NULL,
	HEADS NVARCHAR(100) NULL,
	CYLINDERS NVARCHAR(100) NULL,
	TRACKS NVARCHAR(100) NULL,
	SECTORS NVARCHAR(100) NULL
)
GO

IF OBJECT_ID('LOGICAL_DRIVE') IS NOT NULL
  DROP TABLE LOGICAL_DRIVE
GO

CREATE TABLE LOGICAL_DRIVE(
	HOST_ID INT NOT NULL,
	NAME NVARCHAR(100) NULL,
	DESCRIPTION NVARCHAR(100) NULL,
	SIZE NVARCHAR(100) NULL,
	FREE_SPACE NVARCHAR(100) NULL,
	FILE_SYSTEM NVARCHAR(100) NULL,
	SERIAL_NUMBER NVARCHAR(100) NULL,
	NETWORK_PATH NVARCHAR(100) NULL
)
GO

IF OBJECT_ID('CDROM') IS NOT NULL
  DROP TABLE CDROM
GO

CREATE TABLE CDROM(
	HOST_ID INT NOT NULL,
	NAME NVARCHAR(100) NULL,
	MEDIA_TYPE NVARCHAR(100) NULL,
	MANUFACTURER NVARCHAR(100) NULL,
	NETWORK_PATH NVARCHAR(100) NULL
)
GO

IF OBJECT_ID('VIDEO') IS NOT NULL
  DROP TABLE VIDEO
GO

CREATE TABLE VIDEO(
	HOST_ID INT NOT NULL,
	NAME NVARCHAR(100) NULL,
	CURRENT_HORIZONTAL_RESOLUTION NVARCHAR(100) NULL,
	CURRENT_VERTICAL_RESOLUTION NVARCHAR(100) NULL,
	CURRENT_BITS_PER_PIXEL NVARCHAR(100) NULL,
	CURRENT_REFRESH_RATE NVARCHAR(100) NULL
)
GO

IF OBJECT_ID('PRINTER') IS NOT NULL
  DROP TABLE PRINTER
GO

CREATE TABLE PRINTER(
	HOST_ID INT NOT NULL,
	FIELD1 NVARCHAR(100) NULL,
	FIELD2 NVARCHAR(100) NULL,
	FIELD3 NVARCHAR(100) NULL,
	FIELD4 NVARCHAR(100) NULL
)
GO

IF OBJECT_ID('MULTIMEDIA') IS NOT NULL
  DROP TABLE MULTIMEDIA
GO

CREATE TABLE MULTIMEDIA(
	HOST_ID INT NOT NULL,
	NAME NVARCHAR(100) NULL,
	MANUFACTURER NVARCHAR(100) NULL
)
GO

IF OBJECT_ID('NETWORK_ADAPTER') IS NOT NULL
  DROP TABLE NETWORK_ADAPTER
GO

CREATE TABLE NETWORK_ADAPTER(
	HOST_ID INT NOT NULL,
	ADAPTER_TYPE NVARCHAR(100) NULL,
	NET_CONNECTION_STATUS NVARCHAR(100) NULL,
	MANUFACTURER NVARCHAR(100) NULL,
	SPEED NVARCHAR(100) NULL,
	ADAPTER_IP_ADDRESS NVARCHAR(100) NULL,
	ADAPTER_MAC_ADDRESS NVARCHAR(100) NULL,
	DHCP_ENABLED NVARCHAR(100) NULL,
	DHCP_SERVER NVARCHAR(100) NULL,
	DNS_DOMAIN NVARCHAR(100) NULL,
	WINS_PRIMARY NVARCHAR(100) NULL,
	WINS_SECONDARY NVARCHAR(100) NULL
)
GO

IF OBJECT_ID('SHARE') IS NOT NULL
  DROP TABLE SHARE
GO

CREATE TABLE SHARE(
	HOST_ID INT NOT NULL,
	NAME NVARCHAR(100) NULL, 
	CAPTION NVARCHAR(100) NULL,
	PATH NVARCHAR(100) NULL,
	TYPE NVARCHAR(100) NULL
)
GO

IF OBJECT_ID('HOTFIX') IS NOT NULL
  DROP TABLE HOTFIX
GO

CREATE TABLE HOTFIX(
	HOST_ID INT NOT NULL,
	HOTFIX NVARCHAR(100) NULL
)
GO

IF OBJECT_ID('SOFTWARE') IS NOT NULL
  DROP TABLE SOFTWARE
GO

CREATE TABLE SOFTWARE(
	HOST_ID INT NOT NULL,
	NAME NVARCHAR(255) NULL,
	VERSION NVARCHAR(255) NULL,
	PUBLISHER NVARCHAR(255) NULL,
	SIZE NVARCHAR(100) NULL,
	INSTALL_DATE NVARCHAR(100) NULL
)
GO
